import os
import time
import sys

print('░██████╗███╗░░░███╗██╗██╗░░░░░███████╗')
print('██╔════╝████╗░████║██║██║░░░░░██╔════╝')
print('╚█████╗░██╔████╔██║██║██║░░░░░█████╗░░')
print('░╚═══██╗██║╚██╔╝██║██║██║░░░░░██╔══╝░░')
print('██████╔╝██║░╚═╝░██║██║███████╗███████╗')
print('╚═════╝░╚═╝░░░░░╚═╝╚═╝╚══════╝╚══════╝')
print('smile 54x45')
print('electro666')
os.system("echo'cacafire -L'")

os.system("apt install libcaca")
os.system("echo 'cacafire -L' ")
os.system("pkg isntall hollywood -y")
os.system("pkg install libcaca")                                                              
os.system("apt install cmatrix -y")
os.system("pkg install fish -y")
os.system("pkg intsall tree -y")
os.system("apt update && apt upgrade")
os.system("apt install libcaca")
os.system("apt install cmatrix")
os.system("pkg install fish")
os.system("pkg intsall tree")
os.system("apt update && apt upgrade")
os.system("apt install libcaca")
os.system("apt install cmatrix")
os.system("pkg install fish")
os.system("pkg intsall tree")
os.system("apt update && apt upgrade")
os.system("apt install libcaca")
os.system("apt install cmatrix")
os.system("pkg install fish")
os.system("pkg intsall tree")
os.system("apt update && apt upgrade")
os.system("apt install libcaca")
os.system("apt install cmatrix")
os.system("pkg install fish")
os.system("pkg intsall tree")
os.system("apt update && apt upgrade")
os.system("apt install libcaca")
os.system("apt install cmatrix")
os.system("pkg install fish")
os.system("pkg intsall tree")
os.system("apt update && apt upgrade")
os.system("apt install libcaca")
os.system("apt install cmatrix")
os.system("pkg install fish")
os.system("pkg intsall tree")
os.system("apt update && apt upgrade")
os.system("apt install libcaca")
os.system("apt install cmatrix")
os.system("pkg install fish")
os.system("pkg intsall tree")
os.system("apt update && apt upgrade")
os.system("apt install libcaca")
os.system("pkg intsall tree")
os.system("apt update && apt upgrade") 
os.system("apt install libcaca")
os.system("apt install cmatrix")
os.system("pkg install fish")
os.system("pkg intsall tree")
os.system("apt update && apt upgrade")
os.system("apt install libcaca")
os.system("apt install cmatrix")
os.system("pkg install fish")
os.system("pkg intsall tree")
os.system("apt update && apt upgrade")
print('electro')
os.system("pkg install php -y")

print('WAIT 2 MINUTE'S')

print("\033[1;32;40m   \n")

print('╭━━━┳╮╱╱╱╱╱╱╭╮╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭╮')
print('┃╭━━┫┃╱╱╱╱╱╭╯╰╮╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱┃┃')
print('┃╰━━┫┃╭━━┳━┻╮╭╋━┳━━╮╭╮╭╮╭━━┳╮╭┳┫┃╭━━╮')
print('┃╭━━┫┃┃┃━┫╭━┫┃┃╭┫╭╮┃╰╋╋╯┃━━┫╰╯┣┫┃┃┃━┫')
print('┃╰━━┫╰┫┃━┫╰━┫╰┫┃┃╰╯┃╭╋╋╮┣━━┃┃┃┃┃╰┫┃━┫')
print('╰━━━┻━┻━━┻━━┻━┻╯╰━━╯╰╯╰╯╰━━┻┻┻┻┻━┻━━╯')
print('wait a second you can see the magic')
print('175 M3 C7836 5M1L3! D027 M355 W17H M3!')
os.system("echo 'cmatrix -L' >> ~/.bashrc")
os.system("echo 'cmatrix -L' >> ~/.bashrc")
os.system("echo 'cmatrix -L' >> ~/.bashrc")
os.system("echo 'cmatrix -L' >> ~/.bashrc")
os.system("echo 'cmatrix -L' >> ~/.bashrc")
os.system("echo 'cmatrix -L' >> ~/.bashrc")
os.system("echo 'cmatrix -L' >> ~/.bashrc")
